<?php

namespace ShoppingListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsBoughtRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsBoughtRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getProductsBoughtOrder()
    {
        $qb = $this->createQueryBuilder('pb')
            ->select('pb')
            ->addOrderBy('pb.buyingDate', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
