<?php

namespace ShoppingListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsBoughtRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsBoughtRepository extends EntityRepository
{
    /**
     * @param $productId
     * @return int
     */
    public function getProductQuantity($productId)
    {
        return $this->createQueryBuilder('pb')
            ->select('count(pb.id)')
            ->where('pb.product = :productId')
            ->setParameter('productId', $productId)
            ->getQuery()->getSingleScalarResult();
    }
    /**
     * @return array
     */
    public function getProductsBoughtOrder()
    {
        $qb = $this->createQueryBuilder('pb')
            ->select('pb')
            ->addOrderBy('pb.buyingDate', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
