<?php

namespace ShoppingListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsBoughtRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsBoughtRepository extends EntityRepository
{
}
