shopping_list_default:
    path:     /
    defaults: { _controller: ShoppingListBundle:Default:index }
    options:
        expose: true

shopping_search_products_default:
    path:     /search-products
    defaults: { _controller: ShoppingListBundle:Default:searchProducts }