shopping_list_default:
    path:     /
    defaults: { _controller: ShoppingListBundle:Default:index }
    options:
        expose: true

shopping_search_products_default:
    path:     /search-products
    defaults: { _controller: ShoppingListBundle:Default:searchProducts }

shopping_list_add_product_ajax:
    path:     /add-product
    defaults: { _controller: ShoppingListBundle:Default:addProductAjax }
    methods:  [POST]
    options:
        expose: true