shopping_list_notification_default:
    path:     /notification/{productId}
    defaults: { _controller: ShoppingListBundle:Default:addFromNotification, productId: 0 }
    requirements:
        productId: '\d+'
    options:
        expose: true

shopping_list_default:
    path:     /{productId}
    defaults: { _controller: ShoppingListBundle:Default:index, productId: 0 }
    requirements:
        productId: '\d+'
    options:
        expose: true

shopping_search_products_default:
    path:     /search-products
    defaults: { _controller: ShoppingListBundle:Default:searchProducts }

shopping_list_add_product_ajax:
    path:     /add-product/{productId}
    defaults: { _controller: ShoppingListBundle:Default:addProductAjax, productId: 0 }
    methods:  [POST]
    requirements:
        productId: '\d+'
    options:
        expose: true